const LOGIN = "LOGIN";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILED = "LOGIN_FAILED";
const SET_ERROR_LOGIN = "SET_ERROR_LOGIN"

export { LOGIN, LOGIN_SUCCESS, LOGIN_FAILED, SET_ERROR_LOGIN };
