const OPEN_MODAL = "OPEN_MODAL";
const OPEN_MODAL_SUCCESS = "OPEN_MODAL_SUCCESS";
const CLOSE_MODAL = "CLOSE_MODAL";
const SET_PROGRESS = "SET_PROGRESS";

export { OPEN_MODAL, CLOSE_MODAL, OPEN_MODAL_SUCCESS, SET_PROGRESS };
